apiVersion: v1
kind: Service
metadata:
  labels:
    app: mynodejs-deployment
  name: mynodejs-deployment
  namespace: default
spec:
  ports:
  - nodePort: 30323
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: mynodejs-deployment
  sessionAffinity: None
  type: LoadBalancer