version: '3'
services:
  my-app:
    image: abhijitmorye007/my-app:0.0.2
    ports:
      - 3000:3000
    networks:
      - my-mongo-network
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - mongo-data:/data/db
    networks:
      - my-mongo-network
  mongo-express:
    image: mongo-express
    ports:
      - 8080:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=admin
      - ME_CONFIG_MONGODB_SERVER=mongodb
    networks:
      - my-mongo-network
volumes:
  mongo-data:
    driver: local
networks:
  my-mongo-network
