apiVersion: apps/v1
kind : Deployment
metadata:
  labels:
    app: my-node-js-app-v2
  name: my-node-js-app-v2
  namespace: default
spec:
  replicas: 4
  minReadySeconds: 40
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: my-node-js-app-v2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: my-node-js-app-v2
    spec:
      containers:
      - image: abhijitmorye007/myappnodejsimage:0.0.2
        imagePullPolicy: IfNotPresent
        name: nodejs-webserver-image
      restartPolicy: Always
      terminationGracePeriodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: my-node-js-app-v2-service
  name: my-node-js-app-v2-service
  namespace: default
spec:
  ports:
  - nodePort: 30324
    port: 3000
    targetPort: 3000
    protocol: TCP
  selector:
    app: my-node-js-app-v2
  sessionAffinity: None
  type: LoadBalancer
